Update home/bin/ref

diff --git a/home/exact_bin/executable_ref b/home/exact_bin/executable_ref
--- a/home/exact_bin/executable_ref
+++ b/home/exact_bin/executable_ref
@@ -38,6 +38,10 @@ get_url() {
 interactive() {
   local url
   url="$(cfg_table --return-column=2)"
+  if [[ -z "$url" ]]; then
+    gum log -sl info "Sorry we couldn't help you"
+    exit 1
+  fi
   gum log -sl info opening url "$url"
   open_ref "$url"
 }
@@ -94,7 +98,7 @@ main() {
     get_url "$1"
   else
     if [[ $# -eq 1 ]]; then
-      open_ref "$1"
+      open_ref "$(get_url "$1")"
     else
       interactive
     fi
